Repository elastic/opbeans-go, pull requests merged in 2019-11, with the labels that each got.

#34 even a smaller docker image for the opbeans-go
  .dockerignore
Labels: automation

#35 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#36 ci(jenkins) Update Jenkins badge
  README.md
Labels: automation, ci

#29 ci: release process for the opbeans-go
  .ci/bump-version.sh
  Makefile
Labels: [zube]: In Review, automation, enhancement
